--- 
title: "R Programming in Plain English"
author: "Taylor Rodgers"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-steyle: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "A simple guide to R programming for those without programming experience"
---


# About This Book

I never liked most programming books. The same with most programming courses. The reason is that many of them assume you already have a programming background.

That assumption doesn’t work well with the R programming language. It’s unique because it’s a *statistical* programming language. That means the people often needing to learn it are researchers, statisticians, and data analysts – not computer engineers.

That’s why I wrote this book. I wanted to explain R programming to people who don’t know how to program. I want to strip away all the bloated, technical jargon used in most texts and explain R programming “in plain English.”

It’s hard enough to learn statistics. The same for psychology, business, sociology, medicine, economics, marketing, or whatever you were crazy enough to devote the best years of your life to learning. We don’t need the programming language we use to analyze our data to be as hard to learn as the subject itself.

## Things You Should Know Before Reading

Since R is used mostly for statistics, you should know some statistics before reading this book. For example, I assume you know what a p-value is. The same for confidence intervals, regression analysis, and R-square.

That being said, this book would make a great companion piece to your first statistics class. If your book or professor references code to perform certain calculations, this will help you understand what it's doing.

With that out of the way, let’s begin!
